/**
 * Scenario types following the exact API structure
 */

/**
 * Dimension entity
 * Represents a market dimension (e.g., Price, Quality)
 */
export interface Dimension {
  name: string;
  defaultValue: number; // 0.0 - 1.0
}

/**
 * Consumer dimension entity
 * Consumer's expectation for a specific dimension
 */
export interface ConsumerDimension {
  name: string;
  defaultValue: number; // 0.0 - 1.0
}

/**
 * Consumer entity
 * Represents the target consumer archetype
 */
export interface Consumer {
  id: string;
  name: string;
  age: number;
  budget: number;
  targetAcceptanceScore: number;
}

/**
 * Consumer form data (without id - generated by API)
 */
export interface ConsumerFormData {
  name: string;
  age: number;
  budget: number;
  targetAcceptanceScore: number;
}

/**
 * Dimension entity
 * Represents a market dimension (e.g., Price, Quality)
 */
export interface Dimension {
  id: string;
  name: string;
  displayName: string;
  description: string;
  consumerExpectation: number;
  productInitialOffer: number;
}

/**
 * Effect entity for actions
 * Represents the impact of an action on a dimension
 */
export interface ActionEffect {
  dimensionId: string;
  delta: number;
}

/**
 * Effect entity for events
 * Represents the impact of an event on a dimension
 */
export interface EventEffect {
  dimensionId: string;
  weightMultiplier: number;
}

/**
 * Action entity
 * Represents a marketing action (4P)
 */
export interface Action {
  id: string;
  name: string;
  description: string;
  cost: number;
  category: string;
  isInitiallyLocked: boolean;
  prerequisiteActionId: string | null;
  effects: ActionEffect[];
}

/**
 * Event entity
 * Represents a random market event
 */
export interface Event {
  id: string;
  title: string;
  description: string;
  effects: EventEffect[];
}

/**
 * Scenario entity
 * Complete game scenario configuration
 */
export interface Scenario {
  id: string;
  title: string;
  description: string;
}

/**
 * Detailed Scenario entity
 * Complete scenario with full configuration for visualization
 */
export interface ScenarioDetail {
  id: string;
  title: string;
  description: string;
  consumer: Consumer;
  dimensions: Dimension[];
  actions: Action[];
  events: Event[];
}

/**
 * Form data for creating/editing scenarios
 */
export interface ScenarioFormData {
  name: string;
  description: string;
  dimensions: Dimension[];
  consumer: Consumer;
  actions: Action[];
  events: Event[];
}
